site_name: agptools
nav:
  - Home: index.md
  - Commands: commands.md
  - API reference: api.md
theme: material
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
watch:
  - agp/
